import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import NavBar from "./navbar/page";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Service Charge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <NavBar /> */}
        {children}
      </body>
    </html>
  );
}
